### PR TITLE
add terminal output to style guide

### PR DESCRIPTION
**Pull request by ru-fu**

### CODE REVIEW

**Comment by pmatulis** [comment]
As a general comment to what is going into this guide, I feel like we may be putting too much in (the proverbial "kitchen sink"). I've been working with RST for years and I don't see the point of adding a multitude of extensions, one for terminal output in this case. Should we be having more of a discussion around *why* these extensions are being recommended? Recall that this *is* a style guide.

**Comment by ru-fu** [comment]
Do you mean discussing if we want them in the starter pack, or add an explanation to the style guide on what they should be used for?

I think we definitely should have them in the starter pack (the terminal extension, for example, makes it much easier to show input and output of a command than just normal code blocks, and in addition it breaks up the text with some "graphical" elements, which I find is really important for our CL-based tools). If you disagree, we should probably have a chat to figure out what we actually want. :)

**Comment by pmatulis** [comment]
We should be providing a rationale every time we add anything to the style guide, especially Sphinx extensions. If I understand the purposes of the starter pack and the style guide then they should definitely be in agreement. I suggest that a change should first be made to the style guide (rationale included) and then maybe make a corresponding change to the cheat sheet. The thing with a cheat sheet however is that it doesn't need to be comprehensive in terms of coverage of the style guide. Normally cheat sheets just give the fundamentals. That's my personal expectation anyway.

**Comment by pmatulis** [comment]
Thanks.

**Pull request merged**
